### PR TITLE
Solution in Python

### PR DESCRIPTION
**Pull request by noorafsha08**
Intuition
The Two Sum problem asks us to find two numbers in an array that sum up to a given target value. We need to return the indices of these two numbers.
Approach
A more efficient approach is to use a hash table (unordered_map in C++). We can iterate through the array once, and for each element, check if the target minus the current element exists in the hash table. If it does, we have found a valid pair of numbers. If not, we add the current element to the hash table.

### CODE REVIEW

**Comment by noorafsha08** [comment]
@divcs please mark my verify my pull request for the hacktoberfest

**Comment by noorafsha08** [comment]
please verify it . it doesnot show on my profile @divcs

**Comment by divcs** [comment]
check it again, it should show. I've merged your request already.

**Comment by divcs** [comment]
please make sure, that you run 'git pull' to make sure your forked
repository remains updated to all other changes too

**Pull request merged**
